/* Villa's Properties — índice editorial (Insights / News).
   Fuente única de los artículos: la usan insights.html (listado + filtros) y
   cada post (bloque "seguir leyendo"). Los `external:true` viven en el blog de
   producción; el resto son artículos propios de la V2 con datos de mercado. */
window.VP_POSTS = [
  {
    slug: 'post-prueba-de-publicacion-automatica.html',
    category: 'Mercado',
    title: "Prueba de publicación automática",
    dek: "Un artículo de prueba para verificar que el sistema de publicación funciona de punta a punta.",
    date: '2026-08-19',
    read: '3 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-mapa-metro-cuadrado.html',
    category: 'Mercado',
    title: 'El mapa del metro cuadrado en Tenerife Sur',
    dek: 'De 7.469 €/m² en La Caleta a 2.123 € en el casco de San Miguel: tres veces y media de diferencia dentro de la misma comarca, y a veces del mismo municipio.',
    date: '2026-08-18',
    read: '6 min',
    featured: true,
    accent: 'sand',
    figure: 'chart',
  },
  {
    slug: 'post-anuncio-vs-escritura.html',
    category: 'Venta',
    title: 'Lo que pides y lo que se firma',
    dek: 'El precio de anuncio y el de escritura no son el mismo mercado. En Arona la diferencia media es del 22%; en otros municipios el dato dice algo más incómodo.',
    date: '2026-08-18',
    read: '7 min',
    accent: 'atlantic',
    figure: 'gap',
  },
  {
    slug: 'post-donde-se-vende-de-verdad.html',
    category: 'Inversión',
    title: 'Dónde se vende de verdad en el sur',
    dek: 'Arona firma 4 de cada 10 compraventas de la comarca. Guía de Isora, con precios de Costa Adeje, firma una de cada dieciocho. La liquidez también es un dato.',
    date: '2026-08-18',
    read: '5 min',
    accent: 'ink',
    figure: 'volume',
  },
  {
    slug: 'post-como-valorar-tu-vivienda.html',
    category: 'Guía',
    title: 'Cómo valorar tu vivienda sin engañarte',
    dek: 'Un valorador que te da un número redondo te está vendiendo una ilusión de precisión. Las tres cifras que necesitas y los cinco errores que cuestan meses.',
    date: '2026-08-18',
    read: '8 min',
    accent: 'atlantic',
    figure: 'method',
  },
  {
    slug: 'https://villasproperties.es/blog/4/por-que-tu-casa-no-se-vende-en-tenerife-8',
    category: 'Venta',
    title: 'Por qué tu casa no se vende en Tenerife',
    dek: 'Las propiedades de gama alta (+400.000 €) se estancan por errores evitables de estrategia y precio.',
    date: '2026-06-12',
    read: '5 min',
    external: true,
    accent: 'ink',
    figure: 'method',
  },
  {
    slug: 'https://villasproperties.es/blog/4/el-precio-de-la-vivienda-en-espana-se-ha-incrementado-un-45-en-los-ultimos-diez-anos-7',
    category: 'Mercado',
    title: 'La vivienda en España, +45% en diez años',
    dek: 'Una transformación sin precedentes del mercado y qué significa para tu próxima decisión.',
    date: '2026-05-28',
    read: '4 min',
    external: true,
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'https://villasproperties.es/blog/4/invertir-en-tenerife-por-que-la-seguridad-juridica-es-mas-importante-que-la-rentabilidad-3',
    category: 'Inversión',
    title: 'Seguridad jurídica antes que rentabilidad',
    dek: 'Por qué invertir en Tenerife con la documentación blindada importa más que el yield.',
    date: '2026-04-30',
    read: '6 min',
    external: true,
    accent: 'sand',
    figure: 'gap',
  },
];
