/* Villa's Properties — índice editorial (Insights / News).
   Fuente única de los artículos: la usan insights.html (listado + filtros) y
   cada post (bloque "seguir leyendo"). Los `external:true` viven en el blog de
   producción; el resto son artículos propios de la V2 con datos de mercado. */
window.VP_POSTS = [
  {
    slug: 'post-vender-casa-tenerife-sur.html',
    category: 'Venta',
    title: "Vender casa en Tenerife Sur: precio real, impuestos y plazos",
    dek: "En Tenerife Sur se firma entre un 9% y un 25% por debajo de lo que se pide. Precio real por municipio, cuánto te queda neto, la retención del 3% a no residentes y los plazos de venta.",
    date: '2026-08-25',
    read: '8 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-suelo-urbano-canarias-125000-viviendas.html',
    category: 'Mercado',
    title: "Canarias tiene suelo para 125.000 viviendas. Once mil son casas",
    dek: "El Observatorio Canario de la Vivienda cuenta 125.024 viviendas posibles sin recalificar un metro. Pero solo 11.000 son unifamiliares, y eso explica el precio de la villa en el sur.",
    date: '2026-08-20',
    read: '6 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-por-que-tu-casa-no-se-vende-en-tenerife-8.html',
    category: 'Venta',
    title: "Por qué tu casa no se vende en Tenerife",
    dek: "¿Llevas meses intentando vender tu vivienda en Tenerife Sur sin éxito? No estás solo. Muchas propiedades, especialmente las de gama alta (por encima de 400.000€), se estancan en el mercado por un",
    date: '2025-12-27',
    read: '27 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-el-precio-de-la-vivienda-en-espana-se-ha-incrementado-un-45-en-los-ultimos-diez-anos-7.html',
    category: 'Valoración',
    title: "El precio de la vivienda en España se ha incrementado un 45% en los últimos diez años.",
    dek: "Durante la última década, el mercado inmobiliario español ha experimentado una transformación sin precedentes. Lo que comenzó como una lenta recuperación tras el estallido de la burbuja financier",
    date: '2025-12-27',
    read: '6 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-como-vender-una-casa-fase-2-6.html',
    category: 'Venta',
    title: "Cómo vender una Casa Fase 2",
    dek: "Una vez has analizado el mercado y has tomado la decisión de vender tu casa, comienza una fase crítica: preparar correctamente la operación y decidir cómo vas a gestionarla. En este punto debes v",
    date: '2025-12-13',
    read: '6 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-como-vender-una-casa-5.html',
    category: 'Venta',
    title: "Cómo vender una casa",
    dek: "Antes de poner una vivienda a la venta, hay una decisión estratégica que marca todo el proceso: entender el mercado y fijar un precio realista y defendible. No se trata de “probar suerte”, sino d",
    date: '2025-12-13',
    read: '6 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-de-adeje-al-norte-las-zonas-de-tenerife-que-marcaran-la-revalorizacion-en-2026-4.html',
    category: 'Mercado',
    title: "De Adeje al Norte: Las Zonas de Tenerife que Marcarán la Revalorización en 2026",
    dek: "De Adeje al Norte: Las Zonas de Tenerife que Marcarán la Revalorización en 2026Por el equipo de Villas Properties | Expertos en Tendencias Inmobiliarias de Tenerife",
    date: '2025-12-12',
    read: '4 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-invertir-en-tenerife-por-que-la-seguridad-juridica-es-mas-importante-que-la-rentabilidad-3.html',
    category: 'Inversión',
    title: "Invertir en Tenerife: ¿Por qué la seguridad jurídica es más importante que la rentabilidad?",
    dek: "Invertir en Tenerife: ¿Por qué la seguridad jurídica es más importante que la rentabilidad?",
    date: '2025-12-12',
    read: '4 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-cuanto-vale-realmente-mi-villa-en-tenerife-la-clave-esta-en-la-precision-no-en-la-prisa-2.html',
    category: 'Valoración',
    title: "¿Cuánto vale realmente mi villa en Tenerife? La clave está en la precisión, no en la prisa.",
    dek: "¿Cuánto vale realmente mi villa en Tenerife? La clave está en la precisión, no en la prisa.Por el equipo de Villas Properties | Asesoría en Venta de Lujo en Tenerife",
    date: '2025-12-12',
    read: '4 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-estudio-anual-del-mercado-inmobiliario-1.html',
    category: 'Mercado',
    title: "Estudio Anual del Mercado Inmobiliario",
    dek: "El mercado inmobiliario en Tenerife ha mostrado una tendencia alcista robusta y sostenida durante el último lustro (2020-2025). A cierre de septiembre de 2025, la provincia alcanza máximos histór",
    date: '2025-12-12',
    read: '4 min',
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'post-mapa-metro-cuadrado.html',
    category: 'Mercado',
    title: 'El mapa del metro cuadrado en Tenerife Sur',
    dek: 'De 7.469 €/m² en La Caleta a 2.123 € en el casco de San Miguel: tres veces y media de diferencia dentro de la misma comarca, y a veces del mismo municipio.',
    date: '2026-08-18',
    read: '6 min',
    featured: true,
    accent: 'sand',
    figure: 'chart',
  },
  {
    slug: 'post-anuncio-vs-escritura.html',
    category: 'Venta',
    title: 'Lo que pides y lo que se firma',
    dek: 'El precio de anuncio y el de escritura no son el mismo mercado. En Arona la diferencia media es del 22%; en otros municipios el dato dice algo más incómodo.',
    date: '2026-08-18',
    read: '7 min',
    accent: 'atlantic',
    figure: 'gap',
  },
  {
    slug: 'post-donde-se-vende-de-verdad.html',
    category: 'Inversión',
    title: 'Dónde se vende de verdad en el sur',
    dek: 'Arona firma 4 de cada 10 compraventas de la comarca. Guía de Isora, con precios de Costa Adeje, firma una de cada dieciocho. La liquidez también es un dato.',
    date: '2026-08-18',
    read: '5 min',
    accent: 'ink',
    figure: 'volume',
  },
  {
    slug: 'post-como-valorar-tu-vivienda.html',
    category: 'Guía',
    title: 'Cómo valorar tu vivienda sin engañarte',
    dek: 'Un valorador que te da un número redondo te está vendiendo una ilusión de precisión. Las tres cifras que necesitas y los cinco errores que cuestan meses.',
    date: '2026-08-18',
    read: '8 min',
    accent: 'atlantic',
    figure: 'method',
  },
  {
    slug: 'https://villasproperties.es/blog/4/por-que-tu-casa-no-se-vende-en-tenerife-8',
    category: 'Venta',
    title: 'Por qué tu casa no se vende en Tenerife',
    dek: 'Las propiedades de gama alta (+400.000 €) se estancan por errores evitables de estrategia y precio.',
    date: '2026-06-12',
    read: '5 min',
    external: true,
    accent: 'ink',
    figure: 'method',
  },
  {
    slug: 'https://villasproperties.es/blog/4/el-precio-de-la-vivienda-en-espana-se-ha-incrementado-un-45-en-los-ultimos-diez-anos-7',
    category: 'Mercado',
    title: 'La vivienda en España, +45% en diez años',
    dek: 'Una transformación sin precedentes del mercado y qué significa para tu próxima decisión.',
    date: '2026-05-28',
    read: '4 min',
    external: true,
    accent: 'atlantic',
    figure: 'chart',
  },
  {
    slug: 'https://villasproperties.es/blog/4/invertir-en-tenerife-por-que-la-seguridad-juridica-es-mas-importante-que-la-rentabilidad-3',
    category: 'Inversión',
    title: 'Seguridad jurídica antes que rentabilidad',
    dek: 'Por qué invertir en Tenerife con la documentación blindada importa más que el yield.',
    date: '2026-04-30',
    read: '6 min',
    external: true,
    accent: 'sand',
    figure: 'gap',
  },
];
