(() => {
  const $ = (s) => document.querySelector(s);
  const money = (v) => new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number.isFinite(v)?v:0);
  const num = (v,d=1) => Number.isFinite(v) ? v.toLocaleString('es-ES',{minimumFractionDigits:d,maximumFractionDigits:d}) : '—';
  const esc = (s) => String(s ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const keys=['Name','Price','Area','Market','Rent','Capex','Exit'];
  const defaults={a:{Name:'Ocean Residence',Price:245000,Area:78,Market:3500,Rent:1450,Capex:12000,Exit:285000},b:{Name:'Yield Opportunity',Price:198000,Area:112,Market:2350,Rent:1350,Capex:22000,Exit:255000}};
  const getRaw=(p)=>{const o={};keys.forEach(k=>{const el=$(`#${p}${k}`);o[k]=k==='Name'?(el?.value||`${p.toUpperCase()} asset`):Number(el?.value||0)});return o};
  const calc=(o)=>{const total=o.Price+o.Capex,askPsm=o.Area>0?o.Price/o.Area:0,marketValue=o.Area*o.Market,marketGap=o.Price>0?((marketValue-o.Price)/o.Price)*100:0,grossYield=total>0?((o.Rent*12)/total)*100:0,capexRatio=o.Price>0?(o.Capex/o.Price)*100:0,upside=total>0?((o.Exit-total)/total)*100:0;return {...o,total,askPsm,marketValue,marketGap,grossYield,capexRatio,upside}};
  const winner=(a,b,h=true)=>Math.abs(a-b)<.0001?'tie':((h?a>b:a<b)?'a':'b');
  function render(){const a=calc(getRaw('a')),b=calc(getRaw('b'));const signals=[['Asking €/m²',a.askPsm,b.askPsm,false,`${money(a.askPsm)}/m²`,`${money(b.askPsm)}/m²`],['Gap vs market',a.marketGap,b.marketGap,true,`${num(a.marketGap)}%`,`${num(b.marketGap)}%`],['Gross yield',a.grossYield,b.grossYield,true,`${num(a.grossYield)}%`,`${num(b.grossYield)}%`],['CAPEX / asking',a.capexRatio,b.capexRatio,false,`${num(a.capexRatio)}%`,`${num(b.capexRatio)}%`],['Upside to exit',a.upside,b.upside,true,`${num(a.upside)}%`,`${num(b.upside)}%`]];let sa=0,sb=0;const rows=signals.map(([l,av,bv,h,fa,fb])=>{const w=winner(av,bv,h);if(w==='a')sa++;if(w==='b')sb++;const note=w==='tie'?'Tie':w==='a'?`${esc(a.Name)} leads`:`${esc(b.Name)} leads`;return `<div class="feature-row" style="border-color:rgba(255,255,255,.2)"><span>${w==='a'?'A':w==='b'?'B':'='}</span><div><b>${l}</b><p style="color:#c7cfcb">A · ${fa} &nbsp;&nbsp; B · ${fb} · ${note}</p></div></div>`}).join('');const edge=sa===sb?'Balanced screening':sa>sb?`${esc(a.Name)} leads the screening`:`${esc(b.Name)} leads the screening`;$('#compareSummary').innerHTML=`<div style="display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap"><div><div class="eye">SIGNAL COUNT · HEURISTIC</div><div class="dashtitle" style="margin-top:20px">${edge}</div></div><div style="display:flex;gap:28px"><div><small class="eye">ASSET A</small><div style="font-size:42px;margin-top:8px">${sa}/5</div><div class="muted">${esc(a.Name)}</div></div><div><small class="eye">ASSET B</small><div style="font-size:42px;margin-top:8px">${sb}/5</div><div class="muted">${esc(b.Name)}</div></div></div></div><div class="metrics" style="margin-top:34px"><div class="metric"><small>A · Total capital</small><strong>${money(a.total)}</strong></div><div class="metric"><small>B · Total capital</small><strong>${money(b.total)}</strong></div><div class="metric"><small>A · Market value proxy</small><strong>${money(a.marketValue)}</strong></div><div class="metric"><small>B · Market value proxy</small><strong>${money(b.marketValue)}</strong></div></div><p class="muted" style="margin:20px 0 0">El conteo solo compara cinco señales de screening. No constituye una recomendación de inversión.</p>`;$('#compareTable').innerHTML=rows}
  function writeParams(){const q=new URLSearchParams();['a','b'].forEach(p=>keys.forEach(k=>{const el=$(`#${p}${k}`);if(el)q.set(`${p}${k.toLowerCase()}`,el.value)}));history.replaceState(null,'',`${location.pathname}?${q}`)}
  function readParams(){const q=new URLSearchParams(location.search);if(!q.size)return;['a','b'].forEach(p=>keys.forEach(k=>{const v=q.get(`${p}${k.toLowerCase()}`),el=$(`#${p}${k}`);if(v!==null&&el)el.value=v}))}
  function reset(){['a','b'].forEach(p=>keys.forEach(k=>{const el=$(`#${p}${k}`);if(el)el.value=defaults[p][k]}));history.replaceState(null,'',location.pathname);render();$('#compareStatus').textContent='Demo restaurada.'}
  async function share(){writeParams();render();try{await navigator.clipboard.writeText(location.href);$('#compareStatus').textContent='✓ Enlace del escenario copiado.'}catch{$('#compareStatus').textContent='El escenario está en la URL. Copia la dirección del navegador.'}}
  readParams();render();$('#compareRun')?.addEventListener('click',()=>{render();writeParams();$('#compareStatus').textContent='✓ Comparación actualizada.'});$('#compareShare')?.addEventListener('click',share);$('#compareReset')?.addEventListener('click',reset);$('#compareInputs')?.addEventListener('input',render);
})();