/* Villa's Properties — catálogo de inmuebles (fuente única).
   Datos reales de los anuncios propios de la agencia: superficie, distribución,
   equipamiento, año, orientación, certificado energético, gastos de comunidad y
   fotos (descargadas del anuncio, no hotlinkeadas).

   Lo consumen: el grid de la home y de properties.html (app.js) y la ficha
   individual property.html (property.js).

   `zoneKey` / `zoneId` enlazan con market-data.js para calcular la posición del
   inmueble frente al €/m² real de su microzona. Cuando el barrio no existe como
   tal en el dataset de idealista (Cabo Blanco), se usa la microzona colindante
   más representativa (Cho - Guaza).
   `coords` es la ZONA, no el portal exacto: en una ficha pública no se publica
   la puerta del vendedor. */
window.VP_PROPERTIES = [
  {
    ref: '111258127',
    slug: 'costa-adeje-torviscas',
    title: 'Apartamento reformado con terraza y vistas a la piscina',
    town: 'Adeje',
    zone: 'Torviscas Centro y Alto',
    address: 'Calle Galicia, 5',
    zoneKey: 'adeje',
    zoneId: 'costa-adeje',
    type: 'Apartamento',
    status: 'En venta',
    strategy: 'Vivienda / segunda residencia',
    price: 395000,
    pricePerM2: 4489,
    built: 88,
    useful: 74,
    beds: 2,
    baths: 1,
    floor: 'Bajo interior',
    lift: true,
    orientation: 'Oeste',
    year: 1998,
    condition: 'Segunda mano · buen estado',
    community: 86,
    energy: 'Pendiente de etiqueta',
    features: ['Terraza de 15 m²', 'Armarios empotrados', 'Adaptado a movilidad reducida', 'Sin calefacción'],
    equipment: ['Aire acondicionado', 'Piscina', 'Jardín'],
    highlight: 'Residencial La Pineda, una de las zonas más cotizadas del sur.',
    description: [
      'Apartamento totalmente reformado en Costa Adeje con terraza de 15 m² y vistas a la piscina, ubicado en el conocido residencial La Pineda, una zona muy demandada tanto por su ubicación como por su entorno.',
      'La vivienda ha sido totalmente reformada y ofrece una distribución muy cómoda y funcional: 2 habitaciones, 1 baño, una amplia cocina y un gran salón-comedor con muy buena sensación de espacio y luminosidad.',
      'Uno de sus grandes atractivos es la terraza de 15 m² con vistas a la piscina, perfecta para disfrutar del clima de la zona o crear un espacio exterior para comer y descansar.',
      'Excelente oportunidad como vivienda habitual, segunda residencia o inversión en una de las zonas más cotizadas del sur de Tenerife.',
    ],
    coords: [28.0817, -16.735],
    photos: 13,
    url: 'https://www.idealista.com/pro/villas-properties/inmueble/111258127/',
  },
  {
    ref: '111230958',
    slug: 'cabo-blanco-arona',
    title: 'Apartamento amplio con garaje, trastero y balcón de 12 m²',
    town: 'Arona',
    zone: 'Cabo Blanco',
    address: 'Calle Albariza, 27',
    zoneKey: 'arona',
    zoneId: 'cho-guaza',
    type: 'Apartamento',
    status: 'En venta',
    strategy: 'Vivienda / inversión',
    price: 249000,
    pricePerM2: 2264,
    built: 110,
    useful: 85,
    beds: 2,
    baths: 2,
    floor: '1ª planta exterior',
    lift: true,
    orientation: 'Sur',
    year: 2007,
    condition: 'Segunda mano · buen estado',
    community: 30,
    energy: 'Pendiente de etiqueta',
    features: ['Balcón de 12 m²', 'Plaza de garaje incluida', 'Trastero', 'Armarios empotrados', 'Lavadero en azotea'],
    equipment: [],
    highlight: 'Posibilidad de tercera habitación: metros poco habituales para el precio.',
    description: [
      'Si buscas una vivienda con metros, amplitud y potencial, este apartamento en Cabo Blanco, Arona, merece tu atención.',
      'Cuenta con 85 m² útiles muy bien distribuidos: 2 habitaciones, 2 baños, un salón luminoso y una amplia cocina con espacio suficiente y posibilidad de adaptar una tercera habitación, una ventaja poco habitual en este tipo de inmueble.',
      'Uno de sus grandes atractivos es el balcón de 12 m², ideal para disfrutar de un espacio exterior cómodo. Además, la propiedad incluye plaza de garaje, trastero y cuarto lavadero en la azotea comunitaria: tres extras que suman valor real.',
      'Ubicado en Cabo Blanco, una zona cada vez más demandada por su conexión, servicios y comodidad. Una propiedad con fundamento, recorrido y buena salida comercial.',
    ],
    coords: [28.0575, -16.648],
    photos: 8,
    url: 'https://www.idealista.com/pro/villas-properties/inmueble/111230958/',
  },
  {
    ref: '112230501',
    slug: 'los-abrigos-granadilla',
    title: 'Entreplanta luminosa a un paso del paseo marítimo',
    town: 'Granadilla de Abona',
    zone: 'Los Abrigos',
    address: 'Calle Langosta, 6',
    zoneKey: 'granadilla',
    zoneId: 'los-abrigos',
    type: 'Apartamento',
    status: 'En venta',
    strategy: 'Vivienda / alquiler de larga temporada',
    price: 189000,
    pricePerM2: 3375,
    built: 56,
    useful: 55,
    beds: 2,
    baths: 1,
    floor: 'Entreplanta exterior',
    lift: true,
    orientation: 'Sur',
    year: 2000,
    condition: 'Segunda mano · buen estado',
    community: 22,
    energy: 'Inmueble exento',
    features: ['Cocina abierta equipada', 'Armarios empotrados', 'Adaptado a movilidad reducida', 'Sin calefacción'],
    equipment: [],
    highlight: 'Planta baja elevada: la privacidad y la luz de un primero.',
    description: [
      'Luminoso apartamento en planta baja elevada, situado en el Edificio Tejinaste, en Los Abrigos. Aunque registralmente se encuentra en planta baja, la vivienda está elevada varios metros sobre el nivel de la calle, lo que aporta mayor privacidad, luminosidad y sensación de altura respecto a un bajo convencional.',
      'Dispone de un amplio salón-comedor con cocina abierta totalmente equipada, dos dormitorios —uno principal con cama doble y armarios, y un segundo versátil como habitación, despacho o dormitorio de invitados— y baño completo.',
      'Destaca por su entrada de luz natural, amplitud y distribución práctica: está en condiciones de entrar a vivir, con una sencilla actualización estética si se desea modernizar.',
      'Situado en Los Abrigos, localidad costera del sur, próximo a comercios, restaurantes y al paseo marítimo, con buenas conexiones con El Médano, San Isidro y el aeropuerto Tenerife Sur.',
    ],
    coords: [28.0203, -16.5722],
    photos: 11,
    url: 'https://www.idealista.com/pro/villas-properties/inmueble/112230501/',
  },
  {
    ref: '111734875',
    slug: 'el-fraile-loft',
    title: 'Loft de una habitación, listo para entrar o rentabilizar',
    town: 'Arona',
    zone: 'El Fraile',
    address: 'Calle Gran Canaria, 126',
    zoneKey: 'arona',
    zoneId: 'el-fraile',
    type: 'Apartamento · loft',
    status: 'En venta',
    strategy: 'Inversión',
    price: 139000,
    pricePerM2: 2317,
    built: 60,
    useful: 58,
    beds: 1,
    baths: 1,
    floor: 'Bajo exterior',
    lift: false,
    orientation: 'Sur',
    year: 1982,
    condition: 'Segunda mano · buen estado',
    community: null,
    energy: 'Consumo 382,6 kWh/m² año',
    features: ['Cocina americana integrada', 'Sin escaleras', 'Adaptado a movilidad reducida', 'Sin calefacción'],
    equipment: ['Aire acondicionado'],
    highlight: 'A pocos minutos de Las Galletas, Costa del Silencio y Los Cristianos.',
    description: [
      'Acogedor apartamento tipo loft en El Fraile, una zona práctica y bien comunicada del sur de Tenerife, ideal para una persona sola, una pareja o como inversión.',
      'La vivienda cuenta con aproximadamente 60 m² distribuidos en un espacio cómodo y funcional: 1 habitación, baño completo, cocina americana integrada y un amplio salón que aporta sensación de amplitud.',
      'Está en planta baja, una opción cómoda para el día a día, sin escaleras. Su distribución tipo loft la convierte en una vivienda moderna, sencilla de mantener y muy práctica.',
      'Con servicios cercanos —supermercados, comercios, transporte público, colegios y restauración— y a pocos minutos de Las Galletas, Costa del Silencio y Los Cristianos.',
    ],
    coords: [28.0355, -16.6205],
    photos: 5,
    url: 'https://www.idealista.com/pro/villas-properties/inmueble/111734875/',
  },
  {
    ref: '111928810',
    slug: 'el-fraile-2hab',
    title: 'Loft de dos habitaciones en planta baja',
    town: 'Arona',
    zone: 'El Fraile',
    address: 'Calle Gran Canaria, 126',
    zoneKey: 'arona',
    zoneId: 'el-fraile',
    type: 'Apartamento · loft',
    status: 'En venta',
    strategy: 'Primera vivienda / inversión',
    price: 135000,
    pricePerM2: 2250,
    built: 60,
    useful: 58,
    beds: 2,
    baths: 1,
    floor: 'Bajo exterior',
    lift: false,
    orientation: 'Sur',
    year: 1984,
    condition: 'Segunda mano · buen estado',
    community: null,
    energy: 'Consumo 382,6 kWh/m² año',
    features: ['Cocina integrada', 'Armarios empotrados', 'Sin escaleras', 'Adaptado a movilidad reducida'],
    equipment: [],
    highlight: 'El ticket de entrada más bajo del catálogo, con dos dormitorios.',
    description: [
      'Apartamento tipo loft de aproximadamente 60 m², situado en planta baja en la zona de El Fraile, una ubicación práctica y bien comunicada, con todos los servicios del día a día cerca.',
      'La vivienda cuenta con una distribución funcional que aprovecha muy bien el espacio: 2 habitaciones, 1 baño completo, zona de salón-comedor y cocina integrada, ofreciendo un ambiente cómodo y versátil tanto para vivir como para invertir.',
      'Al estar en planta baja, resulta especialmente cómodo para quienes buscan evitar escaleras o desean una vivienda de fácil acceso.',
      'Una oportunidad interesante para primera vivienda, inversión para alquiler o como propiedad práctica en el sur de Tenerife.',
    ],
    coords: [28.0355, -16.6205],
    photos: 6,
    url: 'https://www.idealista.com/pro/villas-properties/inmueble/111928810/',
  },
];

/* Galerías: assets/img/<slug>/NN.webp, descargadas del anuncio propio. */
window.VP_PROPERTIES.forEach((p) => {
  p.images = Array.from({ length: p.photos }, (_, i) => `assets/img/${p.slug}/${String(i + 1).padStart(2, '0')}.webp`);
  /* Pendiente de producción propia: se rellenan cuando existan. */
  p.video = p.video || null;
  p.floorplans = p.floorplans || [];
  p.tour = p.tour || null;
  p.documents = p.documents || [];
});
