(() => {
  'use strict';
  const $=(s,c=document)=>c.querySelector(s);
  const num=v=>Number(String(v??'').replace(',','.'))||0;
  const euro=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0));
  const pct=v=>`${Number(v||0).toFixed(1)}%`;
  const valuation=$('#valuationForm');
  if(valuation){valuation.addEventListener('submit',e=>{e.preventDefault();const zone=$('#vZone')?.value.trim()||'Tenerife';const type=$('#vType')?.value||'Vivienda';const sqm=num($('#vSqm')?.value);const beds=num($('#vBeds')?.value);const state=$('#vState')?.value||'';const result=$('#valuationResult');if(!result)return;if(!sqm){result.innerHTML='<div class="eye">SCREENING</div><div><h3>Falta la superficie.</h3><p>Introduce los m² para estructurar el activo.</p></div>';return;}result.innerHTML=`<div class="eye">SCREENING PREPARADO</div><div><h3>${type} · ${zone}</h3><p>${sqm} m²${beds?` · ${beds} dormitorios`:''}${state?` · ${state}`:''}. Siguiente paso: contrastar microzona, comparables, documentación y objetivo de venta antes de fijar estrategia.</p></div><a class="eye" href="contact.html">SOLICITAR ANÁLISIS ↗</a>`})}
  const impact=$('#impactForm');if(impact){const calc=()=>{const sqm=num($('#mSqm')?.value),asking=num($('#mPrice')?.value),ideal=num($('#mIdealista')?.value),reg=num($('#mRegistro')?.value),rent=num($('#mRent')?.value),days=num($('#mDays')?.value);const out=$('#impactResult');if(!out||!sqm||!asking)return;const askPsm=asking/sqm;const refs=[ideal,reg].filter(Boolean);const refPsm=refs.reduce((a,b)=>a+b,0)/(refs.length||1);const gap=refPsm?((askPsm/refPsm)-1)*100:0;const annual=rent?sqm*rent*12:0;const gross=annual?annual/asking*100:0;let signal='Neutral';if(gap>8)signal='Above reference';else if(gap<-8)signal='Below reference';out.innerHTML=`<div class="metrics"><div class="metric"><small>Published €/m²</small><strong>${Math.round(askPsm).toLocaleString('es-ES')}</strong></div><div class="metric"><small>Reference gap</small><strong>${gap>=0?'+':''}${pct(gap)}</strong></div><div class="metric"><small>Gross rent signal</small><strong>${gross?pct(gross):'—'}</strong></div><div class="metric"><small>Exposure</small><strong>${days?`${days} días`:'—'}</strong></div></div><p style="margin-top:22px">Lectura inicial: <strong>${signal}</strong>. Esta herramienta es orientativa y no sustituye ACM, tasación ni revisión documental.</p>`};impact.addEventListener('input',calc);impact.addEventListener('submit',e=>{e.preventDefault();calc()});calc()}
  const lab=$('#decisionLab');if(lab){const calc=()=>{const price=num($('#dPrice')?.value),rent=num($('#dRent')?.value),capex=num($('#dCapex')?.value),exit=num($('#dExit')?.value);const out=$('#decisionResult');if(!out||!price)return;const basis=price+capex;const gross=rent?rent*12/basis*100:0;const upside=exit?((exit-basis)/basis)*100:0;out.innerHTML=`<div class="metrics"><div class="metric"><small>Total basis</small><strong>${euro(basis)}</strong></div><div class="metric"><small>Gross yield</small><strong>${gross?pct(gross):'—'}</strong></div><div class="metric"><small>Exit upside</small><strong>${exit?pct(upside):'—'}</strong></div><div class="metric"><small>Decision</small><strong>${gross>=7||upside>=15?'Analyse':'Review'}</strong></div></div>`};lab.addEventListener('input',calc);calc()}
})();